[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.5"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v10.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.13"

[prune]
  go-tests = true
  unused-packages = true
